# Render Blueprint - defines how to deploy the Django backend
services:
  - type: web
    name: smartreach-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.4"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        sync: false
      - key: FRONTEND_URL
        value: "https://frontend-azure-iota-20.vercel.app"
      - key: BACKEND_URL
        sync: false
      - key: GOOGLE_OAUTH2_CLIENT_ID
        sync: false
      - key: GOOGLE_OAUTH2_CLIENT_SECRET
        sync: false
      - key: SMARTREACH_EMAIL_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: smartreach-db
          property: connectionString

databases:
  - name: smartreach-db
    plan: free
    databaseName: smartreach
    user: smartreach_user
